### ISSUE TITLE
Upgrades to the OneUSG Connect system

### ISSUE THREAD

**Issue by karpawich** [Shaun-Regenbaum/OneUSGAutomaticClock#5]
The OneUSG Connect system has undergone upgrades over the weekend that break the code for this repo.

Any plans to refactor the selector values for the latest version?

(Thank you so much for making this, by the way. It is so helpful for students!!)

**Comment by Shaun-Regenbaum** [comment]
Ah thanks for letting me know, im a bit busy this week, but ill definitely get around to it next week!

**Comment by Shaun-Regenbaum** [comment]
Itll also be a good opportunity to fix some things that were broken!

**Comment by Shaun-Regenbaum** [comment]
So I have fixed it! I will upload later today (Hopefully!)

**Comment by Shaun-Regenbaum** [comment]
It should be fixed! Let me know if you find any problems with the new push!

**Comment by karpawich** [comment]
It worked! This error can be thrown after check-out, but it did not appear to affect the successful operation of the system. Thank you so much for updating this!!

```
Traceback (most recent call last):
  File "C:\Users\maxka\Workspaces\Temporary\OneUSGAutomaticClock\clock_manager.py", line 288, in <module>
    clockHoursOut()
  File "C:\Users\maxka\Workspaces\Temporary\OneUSGAutomaticClock\clock_manager.py", line 124, in clockHoursOut
    last_action_text = DRIVER.find_element_by_id(
TypeError: 'WebElement' object is not subscriptable
```
